"""Headless-browser scrape provider for parcelsapp.com (no API key).

parcelsapp.com aggregates 600+ couriers and exposes the result of a lookup via
a single POST to ``https://parcelsapp.com/api/v2/parcels``. That request is
heavily anti-bot protected: the tracking number is obfuscated client-side, an
``x-csrf-token`` is attached, and a large browser-fingerprint blob (``se=``) is
sent — all generated by the page's own JavaScript. Rather than reverse-engineer
that scheme (fragile), we drive the real page with Playwright so the browser
builds the signed request itself, and we simply intercept the JSON response.

Crucial detail: parcelsapp detects headless Chromium (the ``sec-ch-ua`` brand
leaks ``"HeadlessChrome"``) and answers ``{"error":"NO_DATA"}``. Launching the
*system Edge* channel (``SCRAPE_BROWSER_CHANNEL=msedge``, the default) reports a
genuine browser brand and returns real data. The bundled Chromium fallback will
usually be blocked — so when we fall back to it and only see "no data", we fail
LOUDLY rather than masquerading that as a clean negative.

Design notes
------------
* Playwright's sync API can't run inside the asyncio event loop, and on Windows
  its teardown clashes with uvicorn's Proactor loop. So all browser work runs in
  ONE dedicated daemon thread that owns the Playwright instance + a persistent
  browser context, and jobs are serialized through a queue (a context is not
  concurrency-safe). The async ``track()`` submits a job and awaits its result
  without blocking the event loop. The worker self-heals: a dead thread or a
  lost browser/context is respawned on the next request.

This path is inherently best-effort: any failure raises ``ProviderError`` so the
resolver can return an honest "not found" (or fall back to demo data when
``SCRAPE_FALLBACK_MOCK=true``).
"""
from __future__ import annotations

import asyncio
import atexit
import logging
import queue
import threading
import time
from concurrent.futures import Future
from datetime import datetime, timezone
from typing import Optional
from urllib.parse import urlparse

from ..config import Settings
from ..models import (
    Address,
    Carrier,
    EstimatedDelivery,
    Event,
    Metrics,
    TrackResult,
    status_label,
)
from ..normalize import build_milestones
from .base import ProviderError, TrackingProvider

logger = logging.getLogger("tracking_api.scrape")

_TRACK_URL = "https://parcelsapp.com/en/tracking/{number}"
_API_MARK = "parcelsapp.com/api/v2/parcels"
_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
)

# Terminal "no data" responses — parcelsapp has nothing trackable for the number.
_TERMINAL_ERRORS = {
    "NO_DATA", "NO_TRACKER", "INVALID_TRACKING_NUMBER", "NOT_FOUND", "ERROR",
}


def parse_proxy(url: str) -> Optional[dict]:
    """Parse SCRAPE_PROXY (e.g. http://user:pass@host:port) into parts."""
    url = (url or "").strip()
    if not url:
        return None
    from urllib.parse import unquote

    u = urlparse(url if "://" in url else f"http://{url}")
    if not u.hostname:
        return None
    return {
        "scheme": (u.scheme or "http").lower(),
        "host": u.hostname,
        "port": u.port,
        "username": unquote(u.username) if u.username else None,
        "password": unquote(u.password) if u.password else None,
    }


def _is_dead_browser_error(exc: BaseException) -> bool:
    """True if an exception means the browser/context is gone (recycle worker)."""
    s = str(exc).lower()
    return any(
        k in s for k in (
            "has been closed", "browser closed", "target closed", "target page",
            "disconnect", "crashed", "connection closed", "browser has been closed",
        )
    )


# ── status mapping (parcelsapp → our normalized vocabulary) ──────────────────
# parcelsapp's granular ``sub_status`` is the most reliable signal; the
# top-level ``status`` is coarser, and ``archive`` is a *terminal* marker (the
# carrier won't update further) that does NOT by itself imply delivery.
_SUB_STATUS_MAP: dict[str, str] = {
    "delivered": "Delivered",
    "out_for_delivery": "OutForDelivery",
    "outfordelivery": "OutForDelivery",
    "in_transit": "InTransit",
    "transit": "InTransit",
    "info_received": "InfoReceived",
    "pre_transit": "InfoReceived",
    "pending": "InfoReceived",
    "pickup": "AvailableForPickup",
    "ready_for_pickup": "AvailableForPickup",
    "customs": "InTransit",
    "customs_hold": "Exception",
    "failed_attempt": "DeliveryFailure",
    "failed": "DeliveryFailure",
    "delivery_failed": "DeliveryFailure",
    "exception": "Exception",
    "alert": "Exception",
    "returned": "Exception",
    "return_to_sender": "Exception",
    "expired": "Expired",
}
_STATUS_MAP: dict[str, str] = {
    "delivered": "Delivered",
    "transit": "InTransit",
    "in_transit": "InTransit",
    "pickup": "AvailableForPickup",
    "customs": "InTransit",
    "exception": "Exception",
    "expired": "Expired",
    "error": "NotFound",
    "not_found": "NotFound",
    "notfound": "NotFound",
    "pre_transit": "InfoReceived",
    "info_received": "InfoReceived",
    "out_for_delivery": "OutForDelivery",
}

# Best-effort keyword inference from a free-text event description. parcelsapp
# returns event text in the courier's own language, so we cover the most common
# English + German phrasings (the courier set most likely to be encountered).
# Order matters: more specific / later-stage statuses first. Keep tokens SPECIFIC
# — bare substrings like "in delivery" or "collect" match unrelated transit text.
_KEYWORDS: list[tuple[str, tuple[str, ...]]] = [
    ("Delivered", (
        "delivered", "zugestellt", "entregado", "entregue", "livré", "consegnat",
        "доставлен", "已签收", "已投递", "送達", "afgeleverd",
    )),
    ("OutForDelivery", (
        "out for delivery", "out for del", "with delivery courier", "zustellfahrzeug",
        "reparto", "en reparto", "livraison en cours", "на доставк",
    )),
    ("AvailableForPickup", (
        "available for pickup", "ready for pickup", "ready for collection",
        "awaiting collection", "collect from", "collect your", "abholbereit",
        "pickup point", "filiale", "to be picked up",
    )),
    ("DeliveryFailure", (
        "delivery attempt", "attempted delivery", "not available", "failed",
        "notice left", "recipient not", "zustellung nicht", "unsuccessful",
    )),
    ("Exception", (
        "exception", "return to sender", "returned", "retoure", "held in customs",
        "customs hold", "problem", "delay", "verzögerung", "seized",
    )),
    ("InfoReceived", (
        "label created", "shipping label", "electronically", "elektronisch angekündigt",
        "information received", "pending shipping", "awaiting", "data received",
        "pre-advice", "vorangemeldet", "order processed", "shipment information sent",
    )),
]

# A delivery root + a negation token => a FAILED delivery, not a delivery.
# Guards "could not be delivered" / "konnte nicht zugestellt werden" from being
# mis-classified as Delivered by the bare-substring match above.
_DELIVERY_ROOTS = ("deliver", "zugestellt", "entrega", "entregu", "livr", "consegn")
_NEGATIONS = (
    "could not", "couldn't", "can not", "cannot", "can't", "unable", "not be deliver",
    "not delivered", "was not", "wasn't", "no se pudo", "nicht", "non è stat",
    "failed", "unsuccessful", "未能", "退回",
)


def _infer_status_from_text(text: Optional[str]) -> Optional[str]:
    t = (text or "").lower()
    if not t:
        return None
    if any(r in t for r in _DELIVERY_ROOTS) and any(n in t for n in _NEGATIONS):
        return "DeliveryFailure"
    for status, kws in _KEYWORDS:
        if any(k in t for k in kws):
            return status
    return None


# Inferred statuses that are meaningful enough to keep for a terminal "archive"
# parcel (the rest collapse to "Expired").
_ARCHIVE_KEEP = {"Delivered", "Exception", "DeliveryFailure", "AvailableForPickup"}


def _resolve_status(
    parc_status: Optional[str], parc_sub: Optional[str], latest_desc: Optional[str]
) -> str:
    """Map parcelsapp's status fields onto our normalized status vocabulary."""
    sub = (parc_sub or "").strip().lower()
    top = (parc_status or "").strip().lower()
    if sub in _SUB_STATUS_MAP:
        return _SUB_STATUS_MAP[sub]
    if top in _STATUS_MAP:  # note: "archive" is intentionally NOT in this map
        return _STATUS_MAP[top]
    inferred = _infer_status_from_text(latest_desc)
    if top == "archive":
        # Terminal/archived: keep a meaningful inferred signal (delivered,
        # returned/exception, failed attempt, pickup-ready); otherwise it's an
        # expired/stalled parcel with no further updates.
        return inferred if inferred in _ARCHIVE_KEEP else "Expired"
    return inferred or "InTransit"


def _infer_stage(description: Optional[str]) -> str:
    """Per-event stage (drives milestone timestamps + timeline dot colour)."""
    st = _infer_status_from_text(description)
    if st in ("Delivered", "OutForDelivery", "AvailableForPickup", "InfoReceived",
              "Exception", "DeliveryFailure"):
        return st
    return "InTransit"


def _addr_from_str(s: Optional[str]) -> Optional[Address]:
    """Parse a parcelsapp location like 'Longview, TX, US' or 'City, Country'."""
    parts = [p.strip() for p in (s or "").split(",") if p.strip()]
    if not parts:
        return None
    if len(parts) >= 3:
        return Address(city=parts[0], state=parts[1], country=parts[2])
    if len(parts) == 2:
        second = parts[1]
        # A short all-caps token ("TX", "CA") reads as a state; otherwise a country.
        if len(second) <= 3 and second.isupper():
            return Address(city=parts[0], state=second)
        return Address(city=parts[0], country=second)
    return Address(city=parts[0])


def _norm_iso(date: Optional[str]) -> Optional[str]:
    if not isinstance(date, str) or not date.strip():
        return None
    return date.strip()


def _carrier_name(data: dict) -> Optional[str]:
    det = data.get("detectedCarrier") or {}
    if det.get("name"):
        return det["name"]
    carriers = data.get("carriers") or []
    if carriers and isinstance(carriers[0], str):
        return carriers[0]
    services = data.get("services") or []
    if services and isinstance(services[0], dict) and services[0].get("name"):
        return services[0]["name"]
    return None


def _days_transit(data: dict) -> Optional[int]:
    for attr in data.get("attributes") or []:
        if isinstance(attr, dict) and attr.get("l") == "days_transit":
            try:
                return int(str(attr.get("val")).strip())
            except (TypeError, ValueError):
                return None
    return None


def parse_parcels_payload(
    data: dict, number: str, include_raw: bool
) -> Optional[TrackResult]:
    """Parse a ``parcelsapp.com/api/v2/parcels`` JSON body into a TrackResult.

    Pure function (no browser) so it can be unit-tested against real payloads.
    Returns ``None`` when parcelsapp has no trackable data for the number.

    (parcelsapp auto-detects the carrier from the number, so there is no carrier
    hint to honour here — see ``ScrapeProvider.track``.)
    """
    if not isinstance(data, dict):
        return None

    err = data.get("error")
    states = data.get("states") or []
    if not states:
        # No timeline → nothing to show. A terminal error means honest "not found".
        if err and str(err).upper() in _TERMINAL_ERRORS:
            logger.info("scrape: parcelsapp returned %s for %s", err, number)
            return None
        if err:
            raise ProviderError(f"parcelsapp transient state ({err})")
        return None

    # ── events (parcelsapp returns them newest-first) ────────────────────────
    events: list[Event] = []
    for s in states:
        if not isinstance(s, dict):
            continue
        desc = s.get("status")
        loc = s.get("location")
        t = _norm_iso(s.get("date"))
        events.append(
            Event(
                time_utc=t,
                time_iso=t,
                description=desc,
                location=loc,
                stage=_infer_stage(desc),
                address=_addr_from_str(loc),
            )
        )
    # Stable sort newest-first. Date-less events keep their input order and are
    # handled separately below (they must not masquerade as the oldest scan).
    events.sort(key=lambda e: e.time_utc or e.time_iso or "", reverse=True)
    if not events:
        return None

    # Use timestamped events to find the genuine oldest scan; fall back to all.
    timed = [e for e in events if e.time_utc] or events

    # Anchor the oldest scan to "InfoReceived" so the milestone bar gets a start
    # time, unless we already inferred a more specific early stage.
    if timed[-1].stage == "InTransit":
        timed[-1].stage = "InfoReceived"

    latest = events[0]
    status = _resolve_status(data.get("status"), data.get("sub_status"), latest.description)
    is_delivered = status == "Delivered"

    # ── carrier(s) ───────────────────────────────────────────────────────────
    main_name = _carrier_name(data)
    main_carrier = Carrier(name=main_name) if main_name else None
    providers = [
        Carrier(name=n) for n in (data.get("carriers") or []) if isinstance(n, str) and n
    ]

    # ── route ────────────────────────────────────────────────────────────────
    destination = _addr_from_str(data.get("to"))
    # Origin: the oldest *timestamped* scan that carries a physical location.
    origin = None
    for e in reversed(timed):
        if e.address is not None:
            origin = e.address
            break

    # ── estimated delivery / metrics ─────────────────────────────────────────
    edd = None
    if is_delivered and latest.time_utc:
        edd = EstimatedDelivery(source="Official", **{"from": latest.time_utc, "to": latest.time_utc})

    days_transit = _days_transit(data)
    metrics = Metrics(days_of_transit=days_transit) if days_transit is not None else None

    result = TrackResult(
        number=number,
        carrier=main_carrier,
        status=status,
        status_label=status_label(status),
        sub_status=None,
        is_delivered=is_delivered,
        latest_event=latest,
        estimated_delivery=edd,
        origin=origin,
        destination=destination,
        metrics=metrics,
        milestones=build_milestones(events, status),
        events=events,
        providers=providers,
        source="scrape",
        fetched_at=datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        raw=data if include_raw else None,
    )
    return result


class _BrowserWorker:
    """Owns Playwright + a persistent browser context in a single thread.

    Self-healing: a crashed thread or a lost browser/context is respawned on the
    next ``submit()``. Only a truly unrecoverable condition (Playwright not
    installed) is treated as a sticky fatal.
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._q: "queue.Queue" = queue.Queue()
        self._thread: Optional[threading.Thread] = None
        self._start_lock = threading.Lock()
        self._fatal: Optional[str] = None  # sticky ONLY for unrecoverable errors
        self._wanted_channel = (settings.scrape_browser_channel or "").strip()
        # True when the configured real-browser channel failed and we fell back to
        # bundled Chromium — which parcelsapp usually blocks (→ fail loudly).
        self._fallback_chromium = False
        atexit.register(self.shutdown)

    # ── public API (called from the event-loop thread) ──────────────────────
    def submit(self, number: str) -> "Future":
        self._ensure_started()
        if self._fatal:
            fut: Future = Future()
            fut.set_exception(ProviderError(self._fatal))
            return fut
        fut = Future()
        self._q.put((number, fut))
        return fut

    def shutdown(self) -> None:
        t = self._thread
        if t and t.is_alive():
            self._q.put(None)

    # ── worker thread internals ─────────────────────────────────────────────
    def _ensure_started(self) -> None:
        with self._start_lock:
            if self._fatal:
                return
            # Respawn if never started OR if a previous worker died/crashed.
            if self._thread is None or not self._thread.is_alive():
                self._thread = threading.Thread(
                    target=self._run, name="scrape-browser", daemon=True
                )
                self._thread.start()

    def _run(self) -> None:
        try:
            from playwright.sync_api import sync_playwright
        except ImportError:
            self._fatal = "Playwright not installed (pip install playwright)"
            self._drain(self._fatal)
            return

        try:
            with sync_playwright() as p:
                browser = self._launch(p)
                ctx = browser.new_context(
                    user_agent=_UA, locale="en-US",
                    viewport={"width": 1366, "height": 900},
                    **self._context_kwargs(),
                )
                ctx.add_init_script(
                    "Object.defineProperty(navigator,'webdriver',{get:()=>undefined})"
                )
                self._loop(ctx)
                ctx.close()
                browser.close()
        except Exception as exc:  # launch/context failure — recoverable
            logger.warning(
                "scrape: browser worker stopped (%s); will respawn on next request", exc
            )
        finally:
            # Never leave queued jobs hanging: fail any still-pending ones so
            # their callers get a prompt error (the next request respawns us).
            self._drain("scrape browser worker restarted — please retry")

    def _context_kwargs(self) -> dict:
        """Optional outbound proxy for the browser context."""
        pr = parse_proxy(self._settings.scrape_proxy)
        if not pr:
            return {}
        server = f"{pr['scheme']}://{pr['host']}"
        if pr["port"]:
            server += f":{pr['port']}"
        cfg = {"server": server}
        if pr["username"]:
            cfg["username"] = pr["username"]
        if pr["password"]:
            cfg["password"] = pr["password"]
        logger.info("scrape: using proxy %s", server)
        return {"proxy": cfg}

    def _launch(self, p):
        timeout_ms = int(self._settings.scrape_timeout * 1000)
        args = ["--disable-blink-features=AutomationControlled", "--no-first-run"]
        last: Exception | None = None
        # Prefer the system Edge channel (real browser brand — parcelsapp serves
        # NO_DATA to headless Chromium). Fall back to bundled Chromium.
        for channel in (self._wanted_channel or None, None):
            try:
                kwargs = {"headless": self._settings.scrape_headless, "args": args,
                          "timeout": timeout_ms}
                if channel:
                    kwargs["channel"] = channel
                browser = p.chromium.launch(**kwargs)
                self._fallback_chromium = bool(self._wanted_channel) and channel is None
                if self._fallback_chromium:
                    logger.warning(
                        "scrape: configured channel %r unavailable — fell back to bundled "
                        "Chromium, which parcelsapp usually blocks. Install Edge/Chrome.",
                        self._wanted_channel,
                    )
                else:
                    logger.info("scrape: launched browser channel=%s", channel or "chromium")
                return browser
            except Exception as exc:  # noqa: BLE001
                last = exc
        raise RuntimeError(
            f"{last}. Install a browser: `python -m playwright install chrome`."
        )

    def _loop(self, ctx) -> None:
        while True:
            job = self._q.get()
            if job is None:
                return
            number, fut = job
            if fut.set_running_or_notify_cancel() is False:
                continue
            try:
                fut.set_result(self._scrape(ctx, number))
            except Exception as exc:  # noqa: BLE001
                fut.set_exception(exc)
                if _is_dead_browser_error(exc):
                    # The browser/context is gone — exit so the next request
                    # respawns a fresh one instead of failing every job forever.
                    logger.warning("scrape: browser/context lost (%s); recycling worker", exc)
                    return

    def _scrape(self, ctx, number: str) -> dict:
        # Single shared deadline across navigation + polling, so the worker's
        # hard ceiling stays ~scrape_timeout (strictly below track()'s budget).
        timeout_ms = int(self._settings.scrape_timeout * 1000)
        deadline = time.monotonic() + timeout_ms / 1000
        goto_ms = max(5000, int(timeout_ms * 0.6))

        page = ctx.new_page()
        responses: list[dict] = []

        def on_response(resp) -> None:
            if _API_MARK in resp.url and resp.request.method == "POST":
                try:
                    responses.append(resp.json())
                except Exception:  # non-JSON (challenge/redirect) — ignore
                    pass

        page.on("response", on_response)
        try:
            url = _TRACK_URL.format(number=number)
            try:
                page.goto(url, wait_until="domcontentloaded", timeout=goto_ms)
            except Exception as exc:  # noqa: BLE001
                if _is_dead_browser_error(exc):
                    raise
                # Navigation can time out on slow networks but the API call may
                # still have landed; fall through and inspect what we captured.
                logger.info("scrape: navigation issue for %s: %s", number, exc)

            # The page auto-submits and the result lands in one POST. Poll the
            # captured responses until one carries a timeline or a terminal error.
            while time.monotonic() < deadline:
                best = self._pick_response(responses)
                if best is not None:
                    # A "no data" answer from the blocked Chromium fallback is an
                    # anti-bot block, NOT a real negative — surface it loudly.
                    if self._fallback_chromium and str(best.get("error", "")).upper() in _TERMINAL_ERRORS:
                        raise ProviderError(
                            "parcelsapp returned no data on the bundled-Chromium fallback "
                            "(likely an anti-bot block — install system Edge/Chrome)"
                        )
                    logger.info("scrape: captured parcelsapp response for %s", number)
                    return best
                page.wait_for_timeout(1200)

            if responses:
                return responses[-1]  # last word (likely a transient error)
            raise ProviderError(
                f"no parcelsapp API response for {number} "
                f"(anti-bot block, or no system Edge browser available)"
            )
        finally:
            try:
                page.close()
            except Exception:
                pass

    @staticmethod
    def _pick_response(responses: list[dict]) -> Optional[dict]:
        """Return the most useful captured response, or None to keep waiting."""
        for j in responses:
            if isinstance(j, dict) and j.get("states"):
                return j  # real timeline — best possible answer
        for j in responses:
            if isinstance(j, dict) and str(j.get("error", "")).upper() in _TERMINAL_ERRORS:
                return j  # definitive "no data"
        return None

    def _drain(self, msg: str) -> None:
        while True:
            try:
                job = self._q.get_nowait()
            except queue.Empty:
                return
            if job is None:
                continue
            _, fut = job
            if not fut.done():
                fut.set_exception(ProviderError(msg))


class ScrapeProvider(TrackingProvider):
    name = "scrape"

    _worker: Optional[_BrowserWorker] = None  # process-wide singleton

    def __init__(self, settings: Settings) -> None:
        super().__init__(settings)
        if ScrapeProvider._worker is None:
            ScrapeProvider._worker = _BrowserWorker(settings)

    async def track(self, number: str, carrier: Optional[int] = None) -> Optional[TrackResult]:
        # NOTE: ``carrier`` (a 17track carrier code) is intentionally ignored —
        # parcelsapp auto-detects the carrier from the number and the scrape
        # sends only the number, so carrier disambiguation is unsupported here.
        worker = ScrapeProvider._worker
        assert worker is not None
        fut = worker.submit(number)
        budget = self.settings.scrape_timeout + 20  # strictly > the worker ceiling
        try:
            data = await asyncio.wait_for(asyncio.wrap_future(fut), timeout=budget)
        except asyncio.TimeoutError as exc:
            raise ProviderError("scrape timed out") from exc
        except ProviderError:
            raise
        except Exception as exc:  # noqa: BLE001
            raise ProviderError(f"scrape failed: {exc}") from exc

        return parse_parcels_payload(data, number, self.settings.include_raw)
